# Generated by Django 3.1.2 on 2021-04-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.IntegerField()),
                ('store_id', models.IntegerField()),
                ('channel_no', models.CharField(max_length=200)),
                ('module_name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
